#!/bin/bash
#
# script to take screenshot in selected area
#
###

sleep 0.2

filename=$(date +"%Y%m%d_%H%M")".png"
screenshots="/home/sansfont/Pictures/screenshots"
dest="$screenshots/$filename"

# create screenshot
notify-send -u critical "Select screenshot area" -t 1000
scrot -s $filename

# move to shared folder
if [ -f "$filename" ]; then
    mv "$filename" "$dest"
fi

xclip -selection clipboard -target image/png -i $dest

notify-send -u critical "Screenshot $filename saved. File path is copied into clipboard" -t 5000
